export const data = [
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    },
    {
        accountNumbers: '001',
        accountConvenience: true,
        accountType: 'ईतर',
        deposit: '500',
        accountName: 'John Doe',
        accountNameEnglish: 'John',
        commission: '10',
        address: '123 Street',
        sweatCommission: '20',
        memberNo: 'M123',
        accountDate: '2024-01-01',
        accountMobile: '9999999999',
        accountRoute: 'R001',
        accountPhone: '8888888888',
        accountVillage: 'Village A',
        accountTaluka: 'Taluka B',
        accountDistrict: 'District C',
        accountTypeRadio: 'गाय',
        accountMemberTypeRadio: 'सभासद',
        aadhaarnumber: '123456789012',
        accountSheetNumber: 'S001',
        accountGst: 'GST12345',
        accountStatus: 'Active',
        accountCaste: 'हिंदु-मराठा',
        accountnumber: '123456789',
        accountBank: 'Bank XYZ',
        accountEmail: 'john@example.com',
        accountAge: '30',
        accountSex: 'पुरुष'
    }
];